application: steam-price
version: 1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: style

- url: /script
  static_dir: script
  
- url: /images
  static_dir: images

- url: .*
  script: main.py

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: static/\1
  upload: static/(.*\.woff)
