application: steam-price
version: test
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: style

- url: /script
  static_dir: script
  
- url: /images
  static_dir: images

- url: .*
  script: main.py
